language: php

php:
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - hhvm-3.30

matrix:
    allow_failures:
        - php: hhvm-3.30
    fast_finish: true

before_script:
    - composer self-update
    - composer install

script:
 - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
 - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-3.30" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
 - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-3.30" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
 - sh -c 'if [ -n "$CODECLIMATE_REPO_TOKEN" -a "$TRAVIS_PHP_VERSION" != "hhvm-3.30" ]; then vendor/bin/test-reporter --coverage-report=coverage.clover; fi'
